title = "Condition Report Graph Schema"
version = "1.0"

# ====================
# Node Entities
# ====================

[entities.condition_report]
description = "Represents a structured report documenting an observed abnormal event or condition within 
               a plant or operational environment. This entity captures descriptive information provided 
               by plant staff, including the nature, context, and potential implications of the anomaly."
properties = [
    { name = "date",  type = "string"},
    { name = "ID",    type = "string"},
]

# ====================
# Relationships
# ====================

[relationships.refers]
description = "Indicates that a generalized nuclear-relevant entity such as materials, chemical elements 
               and compounds, chemical reactions, failure modes, degradation mechanisms, and components 
               across electrical, hydraulic, and mechanical systems has been explicitly referenced within 
               a condition report"
from_entity = "condition_report"
to_entity = "nuclear_entity"


[relationships.mentions]
description = "Indicates that a specific system, equipment, or component contained in the provided MBSE model 
               has been explicitly referenced within a condition report, establishing a contextual link between 
               the reported abnormal event or condition and the physical or functional asset involved."
from_entity = "condition_report"
to_entity = "mbse_entity"

