title = "Condition Report Graph Schema"
version = 1.0

# ====================
# Node 
# ====================

[node.condition_report]
node_description = """Represents a structured report documenting an observed abnormal event or condition within 
                      a plant or operational environment. This entity captures descriptive information provided 
                      by plant staff, including the nature, context, and potential implications of the anomaly."""

node_properties = [{name = "date",        type = "str",     optional = false, description = 'The timestamp indicating when the condition report was created or issued by the system or analyst'},
                   {name = "ID",          type = "str",     optional = false, description = 'Unique identification number of the condition report'},
                   {name = "conjecture",  type = "boolean", optional = true,  description = 'Indicates if a conjecture is being presented in the text'}]


# ====================
# Relations
# ====================

[relation.refers]
relation_description = """Indicates that a generalized nuclear-relevant entity such as materials, chemical elements 
                          and compounds, chemical reactions, failure modes, degradation mechanisms, and components 
                          across electrical, hydraulic, and mechanical systems has been explicitly referenced within 
                          a condition report."""
from_entity = "condition_report"
to_entity = "nuclear_entity"


[relation.mentions]
relation_description = """Indicates that a specific system, equipment, or component contained in the provided MBSE model 
                          has been explicitly referenced within a condition report, establishing a contextual link between 
                          the reported abnormal event or condition and the physical or functional asset involved."""
from_entity = "condition_report"
to_entity = "mbse_entity"

[relation.temporal_reference]
relation_description = """Indicates that the textual report mentions an explicit or implicit reference to a point or span in time."""
from_entity = "condition_report"
to_entity = "temporal_entity"

