title = "Custom MBSE Model Graph Schema"
version = "1.0"

# ====================
# Node Entities
# ====================

[entities.monitoring_variable]
description = "Represents a measurable physical variable that is continuously or periodically recorded by monitoring 
               sensors from a specific component, equipment, or system. This entity captures dynamic operational 
               data that reflects the real-time or historical state of the asset, enabling monitoring, diagnostics, 
               performance analysis, and integration with predictive models or digital twins within engineering and 
               plant operations contexts."
properties = [
    { name = "label", type = "string", optional = true },
    { name = "ID",    type = "string"},
]

# ====================
# Relationships
# ====================

[relationships.monitors]
description = "Defines a semantic relationship in which a monitoring variable is associated with the performance 
               monitoring of a specific component, equipment, or system. This relation captures the functional 
               linkage between sensor-derived data and the operational behavior of 
               the asset, enabling performance assessment, anomaly detection, and predictive maintenance. 
               It supports traceability between real-time or historical measurements and the physical or logical entities 
               they characterize within the system model."
from_entity = "monitoring_variable"
to_entity = "mbse_entity"