title = "Nuclear Entity Graph Schema"
version = "1.0"

# ====================
# Node Entities
# ====================

[entities.nuclear_entity]
description = "Represents a generalized nuclear-relevant entity that may be referenced in unstructured 
               text authored by plant personnel, encompassing a broad spectrum of technical and 
               operational subjects. These include materials, chemical elements and compounds, chemical 
               reactions, failure modes, degradation mechanisms, and components across electrical, 
               hydraulic, and mechanical systems."
properties = [{ name = "label", type = "string", optional = false, description = "Name of the nucelar entity"},
              { name = "class", type = "string", optional = true,  description = "Category assoiated with the nucelar entity"}
             ]




