title = "sampleSchema"
version = 1.0

# ====================
# Node 
# ====================
[node.cause]
node_description = """causal node"""
node_properties = [{name = "prop1", type = "str", optional = false, description = 'first causal property'},
                   {name = "prop2", type = "int", optional = false, description = 'second causal property'}]

[node.consequence]
node_description = """consequence node"""
node_properties = [{name = "ID_A", type = "bool",  optional = false, description = 'first consequence property'},
                   {name = "ID_B", type = "float", optional = false, description = 'second consequence property'}]

# ====================
# Relations
# ====================
[relation.causality]
relation_description = """Indicates cause-effect relation"""
from_entity = "cause"
to_entity = "consequence"
relation_properties = [{name = "intensity", type = "float", optional = false}]
